accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]


class CustomUser(AbstractUser):
    guardian_name = models.CharField(max_length=120, default='', blank=True)
    guardian_num = models.CharField(max_length=17, blank=True, default='')  # validators should be a list
    Gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    matric = models.CharField(max_length = 20, default = 'LCU/', blank=True)
    DOB = models.DateField(max_length=8, blank=True,null=True)
    Dept = models.CharField(max_length=120, default='', blank=True)
    level = models.CharField(max_length=8, default='', blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list





# class Profile(models.Model):
#     user = models.OneToOneField(AbstractUser, on_delete=models.CASCADE)
#     first_name = models.CharField

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.contrib.auth.forms import UserCreationForm
from .form import CustomUserCreationForm, UserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user
from django.contrib.auth.models import Group
import re
from .models import *


# Create your views here.

def hello_world(request):
    return HttpResponse(f"<h3>Hello {request.user}!</h3>")


@unauthenticated_user
def login_views(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login Successful")
            return redirect('default_home_name')
            # return HttpResponse(f'hello {request.user}')
        else:
            messages.info(request, "Username or Password is incorrect or not inputted")
    context = {}
    return render(request, 'accounts/loginPage.html', context)


@unauthenticated_user
def register_views(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # form.save()
            user = form.save(commit=False)
            user.save()
            user_email = form.cleaned_data.get('email')
            students = re.findall('students', user_email)
            warden = re.findall('warden', user_email)
            print(user_email, type(user_email), '--------------------------')
            print('students' in students)
            if 'students' in students:
                # print('hello student')
                user_group = Group.objects.get(name='student')
                user.groups.add(user_group)
            elif 'warden' in warden:
                # print('hello warden')
                user_group = Group.objects.get(name='warden')
                user.groups.add(user_group)
            else:
                print('error')
                messages.error(request, 'its not a correct email!')
                messages.error(request, 'It should contain username@students.lcu.edu!')
                user.delete()
                return redirect('register_page')
            user_name = form.cleaned_data.get('username')
            # print(user_name)
            messages.success(request, 'Account was successfully created for ' + user_name)
            return redirect('login_page')
    context = {'form': form}
    return render(request, 'accounts/registerPage.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, 'You are successfully logged out')
    return redirect('login_page')


def default_home(request):
    print('default_home')
    group = None
    if request.user.is_anonymous:
        return redirect('login_page')
    else:
        if request.user.groups.exists():
            group = request.user.groups.all()[0].name
            print(group)

            if group == 'student':
                return redirect('home')

            elif group == 'warden':
                return redirect('warden_blocks')
                # return view_func(request, *args, **kwargs)
            elif group == 'chief warden':
                return redirect('chief_warden_home')
            else:
                message = "You are not authorized to view this page"
                messages.info(request, message)
                return redirect('logout_page')
                # return HttpResponse('You are not authorized to view this page')


def updateviews(request):
    if request.method == 'POST':
        uform = UserForm(request.POST)
        if uform.is_valid():
            uform.save()
            # user = form.save(commit=False)
            # user.save()
            return redirect('home')
    else:
         uform = UserForm(instance=request.user)

    return render(request, 'accounts/create.html', {'uform':uform})

accounts/templates/accounts/create.html
<!-- <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<h1 id="title">Bio Data Form</h1>
<div id="form-outer">
  <p id="description">
    To know the details of students
  </p>
  <form id="survey-form" method="GET" action="">
    <div class="rowTab">
      <div class="labels">
        <label id="name-label" for="name">Name: </label>
      </div>
      <div class="rightTab">
        <input autofocus type="text" name="name" id="name" class="input-field" placeholder="Enter your name" required>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label id="fname-label" for="fname">Father's Name: </label>
      </div>
      <div class="rightTab">
        <input autofocus type="text" name="fname" id="fname" class="input-field" placeholder="Enter your father's name" required>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label id="mname-label" for="mname">Mother's Name: </label>
      </div>
      <div class="rightTab">
        <input autofocus type="text" name="mname" id="mname" class="input-field" placeholder="Enter your mother's name" required>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label id="email-label" for="email">Email: </label>
      </div>
      <div class="rightTab">
        <input type="email" name="email" id="email" class="input-field" required placeholder="Enter your Email">
      </div>
    </div>
    <div class="rowTab">
      <div class="labels">
        <label id="number-label" for="age">Age: </label>
      </div>
      <div class="rightTab">
        <input type="number" name="age" id="number" min="1" max="125" class="input-field" placeholder="Age" required>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label id="dob-label" for="dob">D.O.B: </label>
      </div>
      <div class="rightTab">
        <input type="date" name="dob" id="iddob" class="input-field" required>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label for="department">Department: </label>
      </div>
      <div class="rightTab">
        <select id="dropdown" name="department" class="dropdown">
        <option disabled value>Select an option</option>
        <option value="it">IT</option>
        <option value="cse">CSE</option>
        <option value="ece">ECE</option>
        <option value="mech">MECH</option>
        <option value="civil">CIVIL</option>
        <option value="other">Other</option>
        </select>
      </div>
    </div>
    
    <div class="rowTab">
      <div class="labels">
        <label for="gender">Gender: </label>
      </div>
      <div class="rightTab">
        <ul style="list-style: none;">
          <li class="radio"><label><input name="radio-buttons" value="male"  type="radio" class="userRatings" >Male</label></li>
          <li class="radio"><label><input name="radio-buttons" value="female"  type="radio" class="userRatings" >Female</label></li>
          <li class="radio"><label><input name="radio-buttons" value="others"  type="radio" class="userRatings" >Others</label></li>
        </ul>
      </div>
    </div>
    <div class="rowTab">
      <div class="labels">
        <label for="address">Address: </label>
      </div>
      <div class="rightTab">
        <textarea id="comments" class="input-field" style="height:50px;resize:vertical;" name="address" placeholder="Enter your address here..."></textarea>
      </div>
    </div>
    <div class="rowTab">
      <div class="labels">
        <label for="pincode">Pincode: </label>
      </div>
      <div class="rightTab">
       <input type="number" name="pincode" id="idpincode" class="input-field" style="height:20px;resize:vertical;" placeholder="6 - - - - -"></div>
    </div>
    
       <div class="rowTab">
      <div class="labels">
        <label for="language">Language Known: </label>
      </div>
      <div class="rightTab">
        <ul id="language" style="list-style: none;">
          <li class="checkbox"><label><input name="prefer" value="english" type="checkbox" class="userRatings">English</label></li>
          <li class="checkbox"><label><input name="prefer" value="tamil" type="checkbox" class="userRatings">Tamil</label></li>
          <li class="checkbox"><label><input name="prefer" value="hindi" type="checkbox" class="userRatings">Hindi</label></li>
          <li class="checkbox"><label><input name="prefer" value="malayalam" type="checkbox" class="userRatings">Malayalam</label></li>
          <li class="checkbox"><label><input name="prefer" value="kannada" type="checkbox" class="userRatings">Kannada</label></li>
          <li class="checkbox"><label><input name="prefer" value="telugu" type="checkbox" class="userRatings">Telugu</label></li>
          <li class="checkbox"><label><input name="prefer" value="others" type="checkbox" class="userRatings">Others</label></li>
        </ul>
      </div>
    </div>
    
    <button id="submit" type="submit">Submit</button>
    <button id="reset" type="reset">Reset</button>
  </form>
</div> -->

<!-- <form method="post" style="margin-top: 1.3em;" onsubmit = "myFunction()">
         {% csrf_token %}
{{uform.as_p}} -->
<!-- <input type="text" value="{{user.first_name}}"> -->
<!-- <button type="submit">Submit</button>
</form> -->

<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
            <form>

              <div class="row">
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" id="id_username" class="form-control form-control-lg" />
                    <label class="form-label" for="firstName">UserName</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" id="id_first_name" class="form-control form-control-lg" />
                    <label class="form-label" for="lastName">First Name</label>
                  </div>

                </div>

                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" id="id_last_name" class="form-control form-control-lg" />
                    <label class="form-label" for="lastName">Last Name</label>
                  </div>

                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <input type="text" class="form-control form-control-lg" id="id_email"  placeholder="username@students.lcu.edu" />
                    <label for="id_email" class="form-label">Email</label>
                  </div>

                </div>

                
                <div class="col-md-6 mb-4">

                  <h6 class="mb-2 pb-1">Gender: </h6>

                  <select name="Gender" required id="id_Gender">
                    <option value="" selected>---------</option>
                  
                    <option value="Male">Male</option>
                  
                    <option value="Female">Female</option>
                  
                  </select>

                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="email" id="id_Dept" class="form-control form-control-lg" />
                    <label class="form-label" for="emailAddress">Dept</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="tel" id="id_phone_number" class="form-control form-control-lg" />
                    <label class="form-label" for="phoneNumber">Phone Number</label>
                  </div>

                </div>
              </div>

              <div class="row">
                <div class="col-12">

                  <select class="select form-control-lg">
                    <option value="1" disabled>Choose option</option>
                    <option value="2">Subject 1</option>
                    <option value="3">Subject 2</option>
                    <option value="4">Subject 3</option>
                  </select>
                  <label class="form-label select-label">Choose option</label>

                </div>
              </div>

              <div class="mt-4 pt-2">
                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


.gradient-custom {
  /* fallback for old browsers */
  background: #f093fb;
  
  /* Chrome 10-25, Safari 5.1-6 */
  background: -webkit-linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1));
  
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  background: linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1))
  }
  
  .card-registration .select-input.form-control[readonly]:not([disabled]) {
  font-size: 1rem;
  line-height: 2.15;
  padding-left: .75em;
  padding-right: .75em;
  }
  .card-registration .select-arrow {
  top: 13px;
  }

accounts/templates/accounts/loginPage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/LCU.jpg'%}" type="image/x-icon">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">

    <title>Login - Hostel Management Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
       body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
           background-image:url("{% static 'img/bg.jpg'%}");
      background-size: cover;
      background-repeat: no-repeat;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #fff;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            /*color: #fff;*/
            font-size: 20px;
            font-weight: bolder;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #33ccff !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
/*
        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }*/
    </style>

</head>
<body>
                <!-- <h3 id="form-title"> LOGIN</h3> -->
<div class="container h-100">


    <div class="d-flex justify-content-center h-100">
    

        <div class="user_card">
    

            <div class="d-flex justify-content-center">

<img src="{% static 'plugins/images/favicon.jfif' %}" align="center" width="70" height="70" class="rounded-circle">
<br />

            </div>
            <h3 id="form-title" align="center">LOGIN HERE</h3>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>



{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <!-- <div class="alert alert-success alert-dismissible fade show"  style="padding: 10px;
            margin-top: 10px;">
                    <strong color="red">Success!</strong> {{ message }}.

                </div> -->
            {% elif message.tags == 'info' %}
                <div class="alert alert-danger alert-dismissible fade show"  style="padding: 10px;
            margin-top: 10px;">
                    <strong color="red">Error!</strong> {{ message }}.
                 
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
           <!--  <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'register_page' %}" class="ml-2">Sign Up</a>
                </div>

            </div> -->
        </div>
    </div>
</div>
</body>

</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/LCU.jpg'%}" type="image/x-icon">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">

    <title>Hostel Management Portal Registration</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body
      {

           background-image:url("{% static 'img/bg.jpg'%}");
      background-size: cover;
      background-repeat: no-repeat;
      background-position-y: 30%;
      background-position-x:30%;
      height: auto;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: white;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            /*color: #fff;*/
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
footer{
    background-color:black;
    height:9vh;
    color:white;
}
    </style>

</head>

<body>

   
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">CREATE ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>

                   <!--     <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        {{ form.phone_number }}
                    </div> -->

<!-- 
<div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.phone_number }}
                    </div>
 -->

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>


                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>

                </form>
            </div>


            <div>
                {% if form.errors %}
                    <p id="messages">{{ form.errors }}</p>
                {% endif %}
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
            </div>

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
                </div>
            </div>

        </div>
    </div>
</div>



<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'Email..';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>



</body>
</html>
